[PHP]
memory_limit = 512M
post_max_size = 100M
upload_max_filesize = 100M
max_execution_time = 300
variables_order = EGPCS
pcov.directory = .

; Xdebug defaults to "develop"; the XDEBUG_MODE variable still overrides this.
xdebug.mode = "off"
